name: pixez
description: A new Flutter project.

publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.4+174

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.4
  crypto: ^3.0.1
  sqflite: ^2.0.2
  path_provider: ^2.0.8
  shared_preferences: ^2.0.13
  share_plus: ^3.0.4
  permission_handler: ^8.3.0
  archive: ^3.1.11
  url_launcher: ^6.0.18
  bot_toast: ^4.0.1
  package_info: ^2.0.2
  uni_links2: ^0.6.0+2
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  in_app_purchase: ^1.0.9
  flutter_widget_from_html_core: ^0.8.4
  device_info_plus: ^3.0.1
  flutter_displaymode: ^0.3.2
  receive_sharing_intent: ^1.4.5
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  flutter_colorpicker: ^1.0.2
  waterfall_flow: ^3.0.2
  animations: ^2.0.2
  extended_text: ^9.0.0
  font_awesome_flutter: ^9.1.0
  json_annotation: ^4.4.0
  flutter_staggered_animations: ^1.0.0
  badges: ^2.0.1
  image_picker: ^0.8.4+7
  intl: ^0.17.0
  extended_nested_scroll_view: ^3.0.0
  quiver: ^3.0.1+1
  flutter_inappwebview: ^5.3.2
  auto_animated: ^3.0.1
  http: ^0.13.4
#  dio_http_cache: ^0.3.0
  dio_cache_interceptor: ^3.2.2
  photo_view: ^0.13.0
  http_interceptor: 2.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2
  json_serializable: ^6.1.4
  analyzer: ^3.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/host.json
    - assets/emojis/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  generate: true