name: pixez
description: A new Flutter project.

publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.9.3+221

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.1.1
  crypto: ^3.0.2
  sqflite: ^2.2.5
  path_provider: ^2.0.13
  shared_preferences: ^2.0.18
  share_plus: ^6.3.1
  permission_handler: ^10.2.0
  archive: ^3.3.6
  url_launcher: ^6.1.10
  bot_toast: ^4.0.3
  package_info_plus: ^3.0.3
  uni_links2: ^0.6.0+2
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  in_app_purchase: ^3.1.5
  flutter_widget_from_html: ^0.10.0
  device_info_plus: ^8.1.0
  flutter_displaymode: ^0.5.0
  receive_sharing_intent: ^1.4.5
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  flutter_colorpicker: ^1.0.3
  waterfall_flow: ^3.0.2
  animations: ^2.0.7
  extended_text: ^10.0.1
  font_awesome_flutter: ^10.1.0
  json_annotation: ^4.8.0
  flutter_staggered_animations: ^1.1.1
  badges: ^3.0.3
  image_picker: ^0.8.7+1
  intl: ^0.17.0
  quiver: ^3.1.0
  flutter_inappwebview_quill: ^5.4.6
  auto_animated: ^3.1.0
  http: ^0.13.4
  dio_cache_interceptor: ^3.4.1
  photo_view: ^0.14.0
  http_interceptor: 2.0.0-beta.2
  image: ^4.0.15
  easy_refresh: ^3.3.1
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  json_serializable: ^6.6.1
  analyzer: ^5.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/host.json
    - assets/emojis/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  generate: true