name: pixez
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.2+40

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: 3.0.9
  crypto: any
  sqflite: ^1.3.1
  path_provider: ^1.6.11
  shared_preferences: ^0.5.8
  flutter_staggered_grid_view:
    path: plugins/flutter_staggered_grid_view
  cached_network_image: ^2.2.0+1
  flutter_cache_manager: ^1.4.1
  flutter_easyrefresh: ^2.1.1
  share: ^0.6.4+3
  share_extend: ^1.1.9
  permission_handler: ^5.0.1+1
  save_in_gallery: ^0.1.3
  flutter_cupertino_date_picker: ^1.0.26+2
  archive: ^2.0.13
  url_launcher: ^5.5.0
  bot_toast: ^3.0.0
  package_info: ^0.4.1
  json_serializable: ^3.3.0
  uni_links: ^0.4.0
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  flutter_inapp_purchase: ^2.1.2
  photo_view: ^0.9.2
  flutter_html: ^1.0.0
  image_picker: ^0.6.7+4
  extended_nested_scroll_view: ^1.0.0
  scrollable_positioned_list: ^0.1.6
  flutter_date_pickers: ^0.1.0
  device_info: ^0.4.2+4
  provider: ^4.1.3
  flutter_displaymode: ^0.1.0
  receive_sharing_intent: ^1.4.0+2
  like_button: ^1.0.1
  badges: ^1.1.1
  flutter_hooks: ^0.12.0
  flutter_downloader: ^1.4.4
  pull_to_refresh: ^1.6.0
  # flutter_inappwebview: ^4.0.0+4

#dependency_overrides:
#  flutter_svg: ^0.17.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0+1




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/mahou_teriri.jpg
    - assets/splash.gif
    - assets/icon.png
    - assets/no_h.png
    - assets/me.jpg
    - assets/right_now.jpg
    - assets/sustain.png
    - assets/weixin_qr.png
    - assets/h.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: I18n
  main_locale: en_US
  localizely:
    project_id: a588c69e-73a9-44e9-a991-2aa9f1588755
